<a href="https://colab.research.google.com/github/SantanuWorks/PyTorch_Learning/blob/main/1_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic Libraries:

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu118


Tensors: Represents multi-dimensional set of numbers

In [5]:
## Creating Tensors - using torch.Tensor()
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# dimensions of scalar

scalar.ndim

0

In [7]:
# get tensor value as int

scalar.item()

7

In [8]:
# Vector

vector = torch.tensor( [7, 7 ] )
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [9]:
# Create a matrix

mat = torch.tensor(
    [ [1, 2],
    [3, 4] ]
)

print(mat)
print(mat.ndim)
print(mat.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [10]:
# creating a tensor

ten = torch.tensor(
    [ [ [1, 2],
    [3, 4] ],
      [ [5, 6],
    [7, 8] ]
    ]
)

print(ten)
print(ten.ndim)
print(ten.shape)

print("Value at 0: ", ten[0])
print("Value at 1: ", ten[1])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])
Value at 0:  tensor([[1, 2],
        [3, 4]])
Value at 1:  tensor([[5, 6],
        [7, 8]])


In [11]:
# Random Tensors - important for neural network to represent data

# random tensor of size 3x4

random_tensor = torch.rand(3, 3, 3)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.9030, 0.2902, 0.4590],
         [0.0509, 0.6906, 0.5632],
         [0.4834, 0.1827, 0.8343]],

        [[0.4777, 0.8775, 0.5418],
         [0.3442, 0.1954, 0.0163],
         [0.0717, 0.7666, 0.8277]],

        [[0.3481, 0.0172, 0.3002],
         [0.4826, 0.1714, 0.8874],
         [0.0698, 0.4338, 0.1312]]])
3
torch.Size([3, 3, 3])


In [12]:
# tensor for image

image_tensor = torch.rand( size = (38, 38, 2) ) # height, width = 38, two color
image_tensor.shape, image_tensor.ndim

(torch.Size([38, 38, 2]), 3)

In [13]:
# all zero or ones tensor

zero_tensor  = torch.zeros( size=(2, 2) )
one_tensor  = torch.ones( size=(2, 2) )

zero_tensor, one_tensor, zero_tensor+one_tensor

# data type of tenor
zero_tensor.dtype

torch.float32

In [14]:
# create tensor range

ran = torch.arange(-1, 3)
print(ran)

ran = torch.arange(start = -1, end = 1, step = 0.2)
print(ran)

tensor([-1,  0,  1,  2])
tensor([-1.0000e+00, -8.0000e-01, -6.0000e-01, -4.0000e-01, -2.0000e-01,
         5.5511e-17,  2.0000e-01,  4.0000e-01,  6.0000e-01,  8.0000e-01])


In [15]:
# create tensors like - replicate a tensor without define size - copy tensor design

cop = torch.ones_like( input=ran )
cop

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# tensor datatypes

# main errors
# not right datatype
# not right device
# not right shape

float_32_tensor = torch.tensor( [2.3, 1.0, 5.3], dtype = None, device = None, requires_grad = False )
float_32_tensor

tensor([2.3000, 1.0000, 5.3000])

In [17]:
# tensor datatypes
# float 32 sensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.device

(tensor([2.3008, 1.0000, 5.3008], dtype=torch.float16), device(type='cpu'))

In [18]:
# manipulating tensor
# operation with a scalar

some_tensor = torch.tensor([3, 4, 1])
some_tensor

# sum
some_tensor + 12

# mul
some_tensor * 10

# div
some_tensor / 3

# sub
some_tensor - 10

# matrix operations
m1 = torch.tensor( [
    [1, 3],
    [2, 4]
] )

m2 = torch.tensor( [
    [0, 1],
    [0, 1]
] )

# matrix sum
m1 + m2

# matrix sub
m1 - m2

# matrix div
m1 / m2

tensor([[inf, 3.],
        [inf, 4.]])

In [19]:
# multiplication
# 1. element wise
# 2. dot product

# matrix mul - element wise
m1 * m2
torch.mul(m1, m2)

# matrix mul - dot product
torch.matmul(m1, m2)

tensor([[0, 4],
        [0, 6]])

In [20]:
%%time
torch.matmul(m1, m2)

CPU times: user 29 µs, sys: 4 µs, total: 33 µs
Wall time: 36.5 µs


tensor([[0, 4],
        [0, 6]])

two rules for performing matrix multiplicaion

1. inner dimensions must match

   M1(3 X 4) and M2(4, 4) will work - inner 4 and 4 are matching
   
   M1(3 X 4) and M2(3, 4) will not work - shape error

2. output matrix will have the shape of outer dimensions

   M1(3 X 4) * M2(4, 4) = M3(3 X 4)

   M1(5 X 3) * M2(3, 2) = M3(5 X 2)

In [21]:
M1 = torch.rand(size=(3, 5))
M2 = torch.rand(size=(5,3))
M3 = torch.rand(size=(3, 4))

In [22]:
print(M1)
print(M2)

# will work
print(torch.matmul(M1, M2))

# Will not work
# print(torch.matmul(M1, M3))

tensor([[0.9132, 0.6775, 0.1283, 0.7569, 0.4540],
        [0.2783, 0.9926, 0.8647, 0.9560, 0.1208],
        [0.0115, 0.7758, 0.5070, 0.9934, 0.3052]])
tensor([[0.8831, 0.9340, 0.7348],
        [0.0325, 0.4768, 0.0277],
        [0.8119, 0.6330, 0.8187],
        [0.5200, 0.8731, 0.1778],
        [0.4184, 0.4195, 0.2128]])
tensor([[1.5162, 2.1086, 1.0260],
        [1.5277, 2.1659, 1.1356],
        [1.0912, 1.6969, 0.6866]])


In [23]:
# 4 X 3
tensor_a = torch.tensor(
    [
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]
    ]
)

# 3 X 2
tensor_b = torch.tensor(
    [
        [1, 2],
        [2, 3],
        [3, 4]
    ]
)

# output: 4 X 2
torch.matmul(tensor_a, tensor_b)

tensor([[14, 20],
        [20, 29],
        [26, 38],
        [32, 47]])

Transpose of a matrix/tensor is the process of swapping its dimensions

e.g. `transpose of M(3 X 4) will be MT(4 X 3)`

In [24]:
tensor_a = torch.tensor(
    [
        [1, 2, 3],
        [2, 3, 4]
    ]
)
print(tensor_a)
print(tensor_a.shape)

print()

tensor_a_transpose = tensor_a.T
print(tensor_a_transpose)
print(tensor_a_transpose.shape)

tensor([[1, 2, 3],
        [2, 3, 4]])
torch.Size([2, 3])

tensor([[1, 2],
        [2, 3],
        [3, 4]])
torch.Size([3, 2])


Tensor aggregation: Find max, min, mean, etc

In [25]:
ta = torch.arange(1, 4)

In [26]:
# Find the max value

print(ta)
ta.max(), torch.max(ta)

tensor([1, 2, 3])


(tensor(3), tensor(3))

In [27]:
# Find the min value

print(ta)
ta.min(), torch.min(ta)

tensor([1, 2, 3])


(tensor(1), tensor(1))

In [28]:
# Find the mean value

print(ta)
ta.type(torch.float32).mean(), torch.mean(ta.type(torch.float32))

tensor([1, 2, 3])


(tensor(2.), tensor(2.))

In [29]:
# Find the sum value

print(ta)
ta.sum(), torch.sum(ta)

tensor([1, 2, 3])


(tensor(6), tensor(6))

In [30]:
# find positional max and min

# find the position in tensor that has min or max value using argmin() or argmax

tb = torch.tensor([2, 4, -2, 2, 6, 0, 3])
print(tb)

tb.argmin(), tb.argmax()
torch.argmin(tb), torch.argmax(tb)

tensor([ 2,  4, -2,  2,  6,  0,  3])


(tensor(2), tensor(4))

## Reshaping, Stacking, Squeezing, Unsqueezing tensors

- Reshaping: reshapes an tensor a defined shape

- View: return a view of an input tensor of certain shape but keep the same memory as the orignal tensor

- Stacking: combine multiple tensors on the top of each other ( vstack - vertical stacking ) or side by side ( hstack - horizontal stacking )

- Squeeze: removes all one dimensions from a tensor

- Unsqueeze: add one dimension to a target tensor

- Permute: return a view of the input with dimensions permuted(swapped) in a certain way

In [31]:
import torch

In [32]:
x = torch.arange(0, 6, 1)
print(x)
x, x.shape

tensor([0, 1, 2, 3, 4, 5])


(tensor([0, 1, 2, 3, 4, 5]), torch.Size([6]))

In [33]:
# change shape

x_reshape = x.reshape(3, 2)
x_reshape, x_reshape.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 torch.Size([3, 2]))

In [34]:
# change shape

x_reshape = x.reshape(6, 1)
x_reshape, x_reshape.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5]]),
 torch.Size([6, 1]))

In [35]:
# change view

x_new_view = x.view(2, 3)
x, x.shape, x_new_view, x_new_view.shape

(tensor([0, 1, 2, 3, 4, 5]),
 torch.Size([6]),
 tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [36]:
# changing generated view reflects on base view ( as they share same memory )
x_new_view[0][1] = -11
x, x_new_view

(tensor([  0, -11,   2,   3,   4,   5]),
 tensor([[  0, -11,   2],
         [  3,   4,   5]]))

In [37]:
# stack tensors

x_stacked = torch.stack([x, x], dim=1)
x, x_stacked

(tensor([  0, -11,   2,   3,   4,   5]),
 tensor([[  0,   0],
         [-11, -11],
         [  2,   2],
         [  3,   3],
         [  4,   4],
         [  5,   5]]))

In [38]:
# stack tensors

x_stacked = torch.stack([x, x], dim=0)
x, x_stacked

(tensor([  0, -11,   2,   3,   4,   5]),
 tensor([[  0, -11,   2,   3,   4,   5],
         [  0, -11,   2,   3,   4,   5]]))

In [39]:
# stack tensors

x_stacked = torch.hstack([x, x])
x, x_stacked

(tensor([  0, -11,   2,   3,   4,   5]),
 tensor([  0, -11,   2,   3,   4,   5,   0, -11,   2,   3,   4,   5]))

In [40]:
# stack tensors

x_stacked = torch.vstack([x, x])
x, x_stacked

(tensor([  0, -11,   2,   3,   4,   5]),
 tensor([[  0, -11,   2,   3,   4,   5],
         [  0, -11,   2,   3,   4,   5]]))

In [41]:
a = torch.tensor(
    [
        [2, 4, 6],
        [1, 2, 3]
    ]
)

b = torch.tensor(
    [
        [0, 1, 3],
        [3, 4, 5]
    ]
)

a, b

(tensor([[2, 4, 6],
         [1, 2, 3]]),
 tensor([[0, 1, 3],
         [3, 4, 5]]))

In [42]:
# stack tensors

stack_ab = None
stack_ab = torch.stack([a, b], dim=0)
stack_ab

tensor([[[2, 4, 6],
         [1, 2, 3]],

        [[0, 1, 3],
         [3, 4, 5]]])

In [43]:
# stack tensors

stack_ab = torch.stack([a, b], dim=1)
stack_ab

tensor([[[2, 4, 6],
         [0, 1, 3]],

        [[1, 2, 3],
         [3, 4, 5]]])

In [44]:
# stack tensors

stack_ab = None
stack_ab = torch.stack([a, b], dim=2)
stack_ab

tensor([[[2, 0],
         [4, 1],
         [6, 3]],

        [[1, 3],
         [2, 4],
         [3, 5]]])

In [45]:
# stack tensors

stack_ab = torch.hstack([a, b])
stack_ab

tensor([[2, 4, 6, 0, 1, 3],
        [1, 2, 3, 3, 4, 5]])

In [46]:
# stack tensors

stack_ab = torch.vstack([a, b])
stack_ab

tensor([[2, 4, 6],
        [1, 2, 3],
        [0, 1, 3],
        [3, 4, 5]])

In [47]:
x = None
x_reshaped = None

x = torch.tensor([1, 2, 3, 4, 5, 6])
x_reshaped = x.reshape(6, 1)
x, x_reshaped

(tensor([1, 2, 3, 4, 5, 6]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6]]))

In [48]:
# Squeeze - remove the one dimensions

x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]))

In [49]:
x_squeezed = x_reshaped.unsqueeze(dim=0)
x_squeezed, x_squeezed.shape

(tensor([[[1],
          [2],
          [3],
          [4],
          [5],
          [6]]]),
 torch.Size([1, 6, 1]))

In [50]:
# Tensor permute - returns view to a tensor with dimensions permuted

og_image = torch.rand(size=(36, 36, 3)) # height, width, color channerls

permuted_image = og_image.permute(2, 0, 1) # 0->2, 1->0, 2->1
og_image.shape, permuted_image.shape

(torch.Size([36, 36, 3]), torch.Size([3, 36, 36]))

Indexing:

Accessig elements using [] operator

In [51]:
x = torch.arange(1, 10).reshape(1, 3, 3)

x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [52]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
x[0][0], x[0][1], x[0][2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [54]:
x[0][0][0], x[0][0][1], x[0][0][2]

(tensor(1), tensor(2), tensor(3))

In [55]:
for i in range(0, 1):
  for j in range(0, 3):
    for k in range(0, 3):
      print(int(x[i][j][k]), " ", end='')
    print()
  print()

1  2  3  
4  5  6  
7  8  9  



In [56]:
# slicing - indexing using colon(:)
# : to select all elements in a dimension

x[0, :], x[:, :, :]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [57]:
x[0, 0, :], x[0, 1, :], x[0, 2, :]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [58]:
x[0, :, 0], x[0, :, 1], x[0, :, 2]

(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))

In [59]:
x[:, :, 0], x[:, :, 1], x[:, :, 2]

(tensor([[1, 4, 7]]), tensor([[2, 5, 8]]), tensor([[3, 6, 9]]))

In [60]:
for i in range(0, 3):
  for j in range(0, 3):
    print(int(x[:, i, j]), " ", end='')
  print()

1  2  3  
4  5  6  
7  8  9  


In [61]:
# return 3, 4, and 9 from x

int(x[:, 0, 2 ]), int(x[:, 1, 0 ]), int(x[:, 2, 2 ])

(3, 4, 9)

###NumPy - Python Numerical Computing Library - Scientific

Interact Pytorch with NumPy

- NumPy data to PyTorch: `torch.from_numpy(ndarray)`

- PyTorch data to numpy: `torch.Tensor.numpy()`

- data type for pytorch data will same as numpy data, vice versa

- memory is not shared like in views

In [62]:
# import numpy
import numpy as np

# numpy to tensor

array = np.arange(1, 9, 2)
tensor = torch.from_numpy(array)
array, tensor, array.dtype, tensor.dtype,

(array([1, 3, 5, 7]), tensor([1, 3, 5, 7]), dtype('int64'), torch.int64)

In [63]:
array = array + 1
array, tensor

(array([2, 4, 6, 8]), tensor([1, 3, 5, 7]))

In [64]:
# tensor to numpy

tensor = torch.tensor([2, 4, 6, 8])
array = torch.Tensor.numpy(tensor)

array, tensor, array.dtype, tensor.dtype,

(array([2, 4, 6, 8]), tensor([2, 4, 6, 8]), dtype('int64'), torch.int64)

In [65]:
tensor = tensor + 1
array, tensor

(array([2, 4, 6, 8]), tensor([3, 5, 7, 9]))

### How neural network learns:
- start with some randomly guessed values
- perform some operations on them
  - make them more accurate
- update guessed values with newly predicted values
- repeat from start

*Reduce the randomness of values to be more accurate* - pytorch **random seed** concept

Reproducibility: prepare random( more accurate than base random ) values over randoms ( base values )
  - it refers to reproducing same kind of random value from a set of data
  - pytorch provides mechanism to add 'flavour' of one random to another which is created from it
  - new generated values may not be all equal

*if we use only random generator function every time to generate new set of value, everytime we will get a new set of value, less chance of similarity - which is a huge loss to for the neural network as it takes a lot of time to generate a specific state(dataset) if we lost it - reproducing that will take much more time - this is where random seed comes into the picture*

Random Seed:

- it is a numerical value which is used to initialize a pseudorandom number generator

- if a set of random values generated with a random seed X then we can generate similar( not necessarily equal but with similar flavour or distribution ) dataset with the same X.

- this helps to reproduces a state of neural network next time efficiently


In [66]:
random_set_a = torch.rand(3, 3)
random_set_b = torch.rand(3, 3)

random_set_a, random_set_b, random_set_a == random_set_b

(tensor([[0.1197, 0.0746, 0.9430],
         [0.5073, 0.5275, 0.5210],
         [0.5839, 0.8367, 0.5761]]),
 tensor([[0.4361, 0.1932, 0.8122],
         [0.6163, 0.2188, 0.1027],
         [0.2266, 0.4766, 0.5087]]),
 tensor([[False, False, False],
         [False, False, False],
         [False, False, False]]))

In [67]:
# defining a random seed
RANDOM_SEED = 50

# set this random seed
torch.manual_seed(RANDOM_SEED)

# generating first state(tensor)
first_state = torch.rand(2, 3)

# enforcing reproducibility
torch.manual_seed(RANDOM_SEED)

# generating second state(tensor) with same flavour of previous
second_state = torch.rand(2, 3)

print(f"First State: {first_state}")
print()
print(f"Second State: {second_state}")
print()
print(f"Comparing State: {first_state == second_state}")

First State: tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

Second State: tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

Comparing State: tensor([[True, True, True],
        [True, True, True]])


### Choosing GPU over CPU

- GPU provides faster computation over CPU

- we can tensors or models on GPU to make it faster processing

- PyTorch can utilize both CPU and GPU

Agnostic Code: check whether system has gpu or not, if not set up gpu else cpu

some code only uses CPU e.g. NumPy


In [68]:
import torch

torch.cuda.is_available()

True

In [71]:
# Agnostic Code

device = 'cpu'
if torch.cuda.is_available():
  device = 'cuda'
device
torch.cuda.device_count()

1

In [72]:
# create a tensor( by default runs on CPU )
tensor = torch.tensor([1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [74]:
# move tensor from CPU to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [78]:
# if tensor is on GPU, then it can not use numpy
# torch.Tensor.numpy(tensor_on_gpu)

# move tensor from GPU to CPU
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu, tensor_on_cpu.device
tensor_on_cpu.numpy()

array([1, 2, 3])